let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 2)) ? 'Bronze 1'
					: ((user.level >= 2) && (user.level <= 3)) ? 'Bronze 1'
						: ((user.level >= 3) && (user.level <= 10)) ? 'Bronze 2'
							: ((user.level >= 10) && (user.level <= 20)) ? 'Bronze 3'
								: ((user.level >= 20) && (user.level <= 30)) ? 'Bronze 4'
									: ((user.level >= 30) && (user.level <= 40)) ? 'Bronze 5'
										: ((user.level >= 40) && (user.level <= 70)) ? 'Silver 1'
											: ((user.level >= 70) && (user.level <= 85)) ? 'Silver 2'
												: ((user.level >= 85) && (user.level <= 95)) ? 'Silver 3'
													: ((user.level >= 95) && (user.level <= 105)) ? 'Silver 4'
														: ((user.level >= 105) && (user.level <= 125)) ? 'Silver 5'
															: ((user.level >= 125) && (user.level <= 150)) ? 'Gold 1'
																: ((user.level >= 150) && (user.level <= 170)) ? 'Gold 2'
																	: ((user.level >= 170) && (user.level <= 190)) ? 'Gold 3'
																		: ((user.level >= 190) && (user.level <= 210)) ? 'Gold 4'
																			: ((user.level >= 210) && (user.level <= 230)) ? 'Gold 5'
																				: ((user.level >= 240) && (user.level <= 260)) ? 'Platinum 1'
																					: ((user.level >= 260) && (user.level <= 290)) ? 'Platinum 2'
																						: ((user.level >= 290) && (user.level <= 320)) ? 'Platinum 3'
																							: ((user.level >= 320) && (user.level <= 350)) ? 'Platinum 4'
																								: ((user.level >= 350) && (user.level <= 380) ? 'Platinum 5'
																									: ((user.level >= 380) && (user.level <= 410)) ? 'Diamond 1'
																										: ((user.level >= 410) && (user.level <= 450)) ? 'Diamond 2'
																											: ((user.level >= 450) && (user.level <= 500)) ? 'Diamond 3'
																												: ((user.level >= 500) && (user.level <= 550)) ? 'Diamond 4'
																													: ((user.level >= 550) && (user.level <= 600)) ? 'Diamond 5'
																														: ((user.level >= 600) && (user.level <= 700)) ? 'Master'
																															: ((user.level >= 700) && (user.level <= 800)) ? 'Master ✩'
																														: ((user.level >= 800) && (user.level <= 900)) ? 'Master ✩✩'
																												: ((user.level >= 900) && (user.level <= 1000)) ? 'Master ✩✩✩'
																										: ((user.level >= 1000) && (user.level <= 1100)) ? 'Master ✯'
																								: ((user.level >= 1100) && (user.level <= 1225)) ? 'Master ✯✯'
																						: ((user.level >= 1225) && (user.level <= 1340)) ? 'Master ✯✯✯'
																				: ((user.level >= 1340) && (user.level <= 1400)) ? 'GrandMaster'
																		: ((user.level >= 1400) && (user.level <= 1555)) ? 'GrandMaster ✩'
																: ((user.level >= 1555) && (user.level <= 1660)) ? 'GrandMaster ✩✩'
														: ((user.level >= 1660) && (user.level <= 1710)) ? 'GrandMaster ✩✩✩'
												: ((user.level >= 1710) && (user.level <= 1825)) ? 'GrandMaster ✯'
										: ((user.level >= 1825) && (user.level <= 1950)) ? 'GrandMaster ✯✯'
								: ((user.level >= 1950) && (user.level <= 2000)) ? 'GrandMaster ✯✯✯'
						: ((user.level >= 2000) && (user.level = 2220)) : 'Legends'
				: ((user.level >= 2220) : (user.level <= 2500)) ? 'Legends 2'
					: ((user.level >= 2500) && (user.level <= 2700)) ? 'Legends 3'
						: ((user.level >= 2700) && (user.level <= 2900)) ? 'Legends 4'
							: ((user.level >= 2900) && (user.level <= 3100)) ? 'Legends 5'
								: ((user.level >= 3100) && (user.level <= 3300)) ? 'Legends 6'
									: ((user.level >= 3300) && (user.level <= 3600)) ? 'Legends 7'
										: ((user.level >= 3600) && (user.level <= 3900)) ? 'Legends 8'
											: ((user.level >= 3900) && (user.level <= 4200)) ? 'Legends 9'
												: ((user.level >= 4200) && (user.level <= 4450)) ? 'Legends 10'
													: ((user.level >= 4450) && (user.level <= 4700)) ? 'Legends 忍'
														: ((user.level => 4700) && (user.level <= 4900)) ? 'Legends 忍¹'
															: ((user.level => 4900) && (user.level <= 5100)) ? 'Legends 忍²'
																: ((user.level >= 5100) && (user.level <= 5600)) ? 'Legends 忍³'
																	: ((user.level >= 5600) && (user.level <= 6100)) ? 'Legends 忍⁴'
																		: ((user.level >= 6100) && (user.level <= 7000)) ? 'GrandLegends'
																			: ((user.level >= 7000) && (user.level <= 10000)) ? 'GrandLegends 1'
																				: ((user.level >= 10000) && (user.level <= 20000)) ? 'GrandLegends 2'
																					: ((user.level >= 20000) && (user.level <= 30000)) ? 'GrandLegends 3'
																						: ((user.level >= 30000) && (user.level <= 40000)) ? 'GrandLegends 4'
																							: ((user.level >= 40000) && (user.level <= 50000)) ? 'GrandLegends 忍¹'
																								: ((user.level >= 50000) && (user.level <= 60000)) ? 'GrandLegends 忍²'
																									: ((user.level >= 60000) && (user.level <= 70000)) ? 'GrandLegends 忍³'
																										: ((user.level >= 70000) && (user.level <= 80000)) ? 'GrandLegends 忍⁴'
																											: ((user.level >= 80000) && (user.level <= 90000)) ? 'Pro 숒'
																												: ((user.level >= 90000) && (user.level <= 99999999999999)) ? 'Pro × GrandLegends 숒'
																												    : 'PENGCOLI'
    user.role = role
    return true
}

module.exports = handler